"""Pre-authored, deterministic synthetic vulnerability catalog (Telco focus).

Every entry here is hand-written and static -- nothing in this catalog is
generated by an LLM. Each entry adds ONE self-contained synthetic file to the
Superset fork under ``telco_security/``; no real Superset internals are ever
edited. The files model realistic telco/OSS-BSS workloads (subscriber PII, CDR
ingestion, ClickHouse analytics, billing, network-element integration) so the
blue team has a realistic remediation target.

The catalog is the contract between red and blue: ``remediation`` is what the
GitHub issue tells Devin to do, and ``category``/``severity`` drive the labels
and the dashboard breakdown.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

BASE_DIR = "telco_security"

BANNER = (
    "# SYNTHETIC PURPLE-TEAM ARTIFACT -- intentionally vulnerable.\n"
    "# Injected by the red-team service of devin-purple-team.\n"
    "# This file is NOT part of upstream Apache Superset.\n"
)


@dataclass(frozen=True)
class Vulnerability:
    """A single deterministic catalog entry."""

    vuln_id: str
    title: str
    description: str
    severity: str
    category: str
    cwe: str
    file_path: str
    content: str
    remediation: str
    detection_hint: str = ""
    tags: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "vuln_id": self.vuln_id,
            "title": self.title,
            "description": self.description,
            "severity": self.severity,
            "category": self.category,
            "cwe": self.cwe,
            "file_path": self.file_path,
            "branch_pattern": f"red-team/{self.vuln_id}/run-<n>",
            "content": self.content,
            "remediation": self.remediation,
            "detection_hint": self.detection_hint,
            "tags": self.tags,
        }

    def branch_for(self, instance: int) -> str:
        """Return the branch name for a numbered injection instance."""

        return f"red-team/{self.vuln_id}/run-{instance}"


CATALOG: list[Vulnerability] = [
    Vulnerability(
        vuln_id="tel-001-md5-subscriber-pii",
        title="Legacy MD5 hashing in subscriber PII masking utility",
        description=(
            "The subscriber PII masking helper pseudonymises IMSI, MSISDN and "
            "ICCID values with unsalted MD5. MD5 is collision-prone and "
            "trivially reversible for the small, structured keyspace of a "
            "national numbering plan, so 'masked' subscriber identifiers can "
            "be recovered with a rainbow table in seconds. Masked exports are "
            "shared with roaming partners, so this is a direct PII exposure."
        ),
        severity="high",
        category="pii_exposure",
        cwe="CWE-327",
        file_path=f"{BASE_DIR}/pii/subscriber_masking.py",
        remediation=(
            "Replace MD5 with a salted, memory-hard KDF (scrypt/argon2 via "
            "`hashlib.scrypt` or `passlib`) or an HMAC-SHA256 keyed with a "
            "secret pepper loaded from the environment. Keep the output "
            "format stable so downstream exports do not break, and add a unit "
            "test asserting the same MSISDN yields different digests under "
            "different peppers."
        ),
        detection_hint="hashlib.md5( on subscriber identifiers",
        tags=["pii", "crypto", "subscriber"],
        content=BANNER
        + '''"""Subscriber PII masking used before sharing datasets with partners."""

import hashlib


def mask_msisdn(msisdn: str) -> str:
    """Pseudonymise a subscriber MSISDN for partner-facing exports."""
    return hashlib.md5(msisdn.encode("utf-8")).hexdigest()


def mask_imsi(imsi: str) -> str:
    """Pseudonymise an IMSI for analytics datasets."""
    return hashlib.md5(imsi.encode("utf-8")).hexdigest()


def mask_iccid(iccid: str) -> str:
    """Pseudonymise a SIM ICCID."""
    return hashlib.md5(iccid.encode("utf-8")).hexdigest()


def mask_subscriber_record(record: dict) -> dict:
    """Return a copy of a subscriber record with identifiers masked."""
    masked = dict(record)
    if "msisdn" in masked:
        masked["msisdn"] = mask_msisdn(masked["msisdn"])
    if "imsi" in masked:
        masked["imsi"] = mask_imsi(masked["imsi"])
    if "iccid" in masked:
        masked["iccid"] = mask_iccid(masked["iccid"])
    return masked
''',
    ),
    Vulnerability(
        vuln_id="tel-002-vulnerable-dependency",
        title="Known-vulnerable pinned dependency enables remote code execution",
        description=(
            "The telco analytics add-on pins PyYAML 5.3.1 (CVE-2020-14343, "
            "arbitrary code execution via `yaml.load` with the default "
            "loader), Jinja2 2.11.2 (CVE-2020-28493 ReDoS) and requests "
            "2.19.1 (CVE-2018-18074 credential leak on redirect). Any "
            "deployment installing this requirements file inherits a "
            "documented RCE path."
        ),
        severity="critical",
        category="rce_dependency",
        cwe="CWE-1104",
        file_path=f"{BASE_DIR}/requirements.txt",
        remediation=(
            "Bump every pin to a patched release (PyYAML>=6.0.1, "
            "Jinja2>=3.1.4, requests>=2.32.0) and verify nothing in "
            "`telco_security/` relies on the removed APIs. Add a "
            "`pip-audit`/`safety` step so a known-vulnerable pin fails CI "
            "instead of shipping."
        ),
        detection_hint="PyYAML==5.3.1 pinned in telco_security/requirements.txt",
        tags=["dependency", "rce", "supply-chain"],
        content='''# SYNTHETIC PURPLE-TEAM ARTIFACT -- intentionally vulnerable pins.
# Injected by the red-team service of devin-purple-team.
# This file is NOT part of upstream Apache Superset.
#
# Telco analytics add-on dependencies.
PyYAML==5.3.1
Jinja2==2.11.2
requests==2.19.1
''',
    ),
    Vulnerability(
        vuln_id="tel-003-clickhouse-query-injection",
        title="Unsanitized input vector in ClickHouse CDR query parser",
        description=(
            "The ClickHouse query builder for the CDR analytics dashboard "
            "interpolates caller-supplied `msisdn`, `cell_id` and `order_by` "
            "values straight into SQL with f-strings. A crafted filter value "
            "can terminate the predicate and append arbitrary SQL, exposing "
            "every subscriber's call detail records."
        ),
        severity="critical",
        category="query_injection",
        cwe="CWE-89",
        file_path=f"{BASE_DIR}/analytics/clickhouse_query_parser.py",
        remediation=(
            "Use ClickHouse parameterised queries (`{name:String}` bindings "
            "with a params dict) for all user-supplied values, and validate "
            "`order_by`/`limit` against an allow-list of column names and an "
            "integer bound. Never build predicates with f-strings."
        ),
        detection_hint="f-string SQL construction in build_cdr_query",
        tags=["injection", "clickhouse", "cdr"],
        content=BANNER
        + '''"""ClickHouse query builder for the CDR analytics dashboard."""


def build_cdr_query(msisdn: str, cell_id: str, order_by: str, limit: str) -> str:
    """Build a call-detail-record lookup query from dashboard filters."""
    return (
        "SELECT call_start, msisdn, cell_id, duration_sec, charge_amount "
        "FROM telco.cdr "
        f"WHERE msisdn = '{msisdn}' AND cell_id = '{cell_id}' "
        f"ORDER BY {order_by} "
        f"LIMIT {limit}"
    )


def build_roaming_query(partner_plmn: str, date_filter: str) -> str:
    """Build a roaming usage query for a partner network."""
    return (
        "SELECT partner_plmn, sum(duration_sec) AS total "
        "FROM telco.roaming_cdr "
        f"WHERE partner_plmn = '{partner_plmn}' AND {date_filter} "
        "GROUP BY partner_plmn"
    )


def run_query(client, sql: str):
    """Execute a pre-built query against ClickHouse."""
    return client.execute(sql)
''',
    ),
    Vulnerability(
        vuln_id="tel-004-hardcoded-credentials",
        title="Hardcoded credentials and API keys in OSS/BSS client config",
        description=(
            "The OSS/BSS integration client ships live-looking credentials in "
            "source: a ClickHouse password, an HSS provisioning API key, an "
            "object-store key pair and a JWT signing secret. Anyone with read "
            "access to the fork -- including CI logs and forks-of-forks -- "
            "obtains production-shaped secrets."
        ),
        severity="critical",
        category="secrets_exposure",
        cwe="CWE-798",
        file_path=f"{BASE_DIR}/config/ossbss_client_config.py",
        remediation=(
            "Delete every literal secret and read them from environment "
            "variables (or a secrets manager) with no fallback default; fail "
            "fast at startup when one is missing. Rotate anything that was "
            "committed and add a secret-scanning pre-commit hook / CI gate."
        ),
        detection_hint="literal API keys and passwords assigned at module scope",
        tags=["secrets", "config", "ossbss"],
        content=BANNER
        + '''"""Configuration for the OSS/BSS integration client."""

CLICKHOUSE_HOST = "clickhouse.telco.internal"
CLICKHOUSE_USER = "cdr_analytics"
CLICKHOUSE_PASSWORD = "Sup3rS3cret-CDR-2019!"

HSS_PROVISIONING_API_KEY = "hss_live_8f4a2c19d7e64b0aa1c35e77b9d02f61"
BILLING_GATEWAY_TOKEN = "bg_prod_5c1e9a8347fd4b2f9e6d0c7a4b83e215"

CDR_ARCHIVE_ACCESS_KEY = "cdr-archive-rw"
CDR_ARCHIVE_SECRET_KEY = "archive-2019-nightly-dump"

JWT_SIGNING_SECRET = "telco-portal-signing-secret"


def clickhouse_dsn() -> str:
    """Return the ClickHouse DSN used by the analytics workers."""
    return (
        f"clickhouse://{CLICKHOUSE_USER}:{CLICKHOUSE_PASSWORD}"
        f"@{CLICKHOUSE_HOST}:9000/telco"
    )


def hss_headers() -> dict:
    """Return auth headers for the HSS provisioning API."""
    return {"X-Api-Key": HSS_PROVISIONING_API_KEY}
''',
    ),
    Vulnerability(
        vuln_id="tel-005-insecure-deserialization-cdr",
        title="Insecure deserialization in CDR ingestion module",
        description=(
            "The CDR ingestion worker unpickles mediation-layer batches and "
            "`yaml.load`s per-operator mediation rules with the unsafe "
            "loader. Both paths execute arbitrary code contained in the "
            "payload, and the mediation feed is reachable from partner "
            "networks -- a hostile roaming partner gets code execution on the "
            "ingestion host."
        ),
        severity="critical",
        category="insecure_deserialization",
        cwe="CWE-502",
        file_path=f"{BASE_DIR}/ingestion/cdr_ingest.py",
        remediation=(
            "Replace `pickle.loads` with a schema-validated format (JSON plus "
            "a Pydantic model, or Avro/Protobuf) and switch `yaml.load` to "
            "`yaml.safe_load`. Reject payloads that fail schema validation and "
            "authenticate the mediation feed."
        ),
        detection_hint="pickle.loads and yaml.load(..., Loader=yaml.Loader)",
        tags=["deserialization", "cdr", "ingestion"],
        content=BANNER
        + '''"""Call-detail-record ingestion from the mediation layer."""

import pickle

import yaml


def load_cdr_batch(payload: bytes):
    """Deserialize a CDR batch pushed by the mediation layer."""
    return pickle.loads(payload)


def load_mediation_rules(raw_yaml: str) -> dict:
    """Load per-operator mediation rules supplied with the batch."""
    return yaml.load(raw_yaml, Loader=yaml.Loader)


def ingest(payload: bytes, raw_rules: str) -> list:
    """Normalise a CDR batch using the supplied mediation rules."""
    records = load_cdr_batch(payload)
    rules = load_mediation_rules(raw_rules)
    rate = rules.get("rate_per_minute", 0.0)
    normalised = []
    for record in records:
        normalised.append(
            {
                "msisdn": record.get("msisdn"),
                "duration_sec": record.get("duration_sec", 0),
                "charge_amount": record.get("duration_sec", 0) / 60.0 * rate,
            }
        )
    return normalised
''',
    ),
    Vulnerability(
        vuln_id="tel-006-jwt-auth-bypass",
        title="Weak JWT signature verification allows auth bypass",
        description=(
            "The subscriber self-care API decodes bearer tokens with "
            "`verify_signature=False` and accepts the `none` algorithm, then "
            "trusts the `role` claim for authorisation. Any caller can mint an "
            "unsigned token claiming `role=admin` and read or modify any "
            "subscriber's plan and billing data."
        ),
        severity="critical",
        category="auth_bypass",
        cwe="CWE-347",
        file_path=f"{BASE_DIR}/api/subscriber_auth.py",
        remediation=(
            "Verify signatures with an explicit algorithm allow-list "
            "(`algorithms=['RS256']` or HS256 with a strong env-provided "
            "secret), enable `exp`/`aud`/`iss` validation, and reject the "
            "`none` algorithm. Authorise on a server-side role lookup rather "
            "than a client-supplied claim."
        ),
        detection_hint='jwt.decode(..., options={"verify_signature": False})',
        tags=["auth", "jwt", "api"],
        content=BANNER
        + '''"""Subscriber self-care API authentication handler."""

import jwt


def decode_token(token: str) -> dict:
    """Decode a subscriber bearer token."""
    return jwt.decode(
        token,
        options={"verify_signature": False, "verify_exp": False},
        algorithms=["HS256", "none"],
    )


def current_subscriber(authorization_header: str) -> dict:
    """Resolve the calling subscriber from the Authorization header."""
    token = authorization_header.replace("Bearer ", "", 1).strip()
    claims = decode_token(token)
    return {
        "msisdn": claims.get("msisdn"),
        "account_id": claims.get("account_id"),
        "role": claims.get("role", "subscriber"),
    }


def require_admin(authorization_header: str) -> dict:
    """Authorise an administrative self-care operation."""
    subscriber = current_subscriber(authorization_header)
    if subscriber["role"] != "admin":
        raise PermissionError("admin role required")
    return subscriber
''',
    ),
    Vulnerability(
        vuln_id="tel-007-ssrf-network-element",
        title="SSRF in OSS network-element integration endpoint",
        description=(
            "The network-element probe endpoint fetches an operator-supplied "
            "URL with no scheme or host restrictions and returns the response "
            "body to the caller. From inside the OSS VPC this reaches cloud "
            "metadata (169.254.169.254), internal HSS/PCRF admin panels and "
            "`file://` paths, turning a diagnostics helper into a full SSRF "
            "read primitive."
        ),
        severity="high",
        category="ssrf",
        cwe="CWE-918",
        file_path=f"{BASE_DIR}/integrations/network_element_probe.py",
        remediation=(
            "Resolve the target host and validate it against an allow-list of "
            "known network elements, reject non-http(s) schemes and any "
            "address that resolves to a private/link-local/loopback range "
            "(re-check after redirects, or disable redirects), and set a "
            "timeout. Do not echo raw response bodies back to the caller."
        ),
        detection_hint="requests.get on a caller-controlled URL with no validation",
        tags=["ssrf", "oss", "integration"],
        content=BANNER
        + '''"""Diagnostics probe for OSS network elements (eNodeB, HSS, PCRF)."""

import requests


def probe_network_element(target_url: str) -> dict:
    """Fetch a status document from a network element and return it."""
    response = requests.get(target_url)
    return {
        "status_code": response.status_code,
        "headers": dict(response.headers),
        "body": response.text,
    }


def bulk_probe(target_urls: list) -> list:
    """Probe several network elements in sequence."""
    return [probe_network_element(url) for url in target_urls]
''',
    ),
    Vulnerability(
        vuln_id="tel-008-path-traversal-billing",
        title="Path traversal in billing report download handler",
        description=(
            "The billing report download handler joins a caller-supplied "
            "`report_name` onto the invoice archive root with no "
            "normalisation, so `../../etc/passwd` or `../<other-account>/` "
            "escapes the account's directory. Any authenticated subscriber can "
            "read other customers' invoices and arbitrary host files."
        ),
        severity="high",
        category="path_traversal",
        cwe="CWE-22",
        file_path=f"{BASE_DIR}/billing/report_download.py",
        remediation=(
            "Resolve the joined path with `Path.resolve()` and require it to "
            "be relative to the account's report root (`is_relative_to`), or "
            "look the report up by opaque ID in a database instead of by "
            "filename. Reject names containing separators or `..`."
        ),
        detection_hint="os.path.join(REPORT_ROOT, account_id, report_name)",
        tags=["path-traversal", "billing"],
        content=BANNER
        + '''"""Billing report download handler for the subscriber portal."""

import os

REPORT_ROOT = "/var/telco/billing/reports"


def resolve_report_path(account_id: str, report_name: str) -> str:
    """Resolve the on-disk path of a subscriber billing report."""
    return os.path.join(REPORT_ROOT, account_id, report_name)


def download_report(account_id: str, report_name: str) -> bytes:
    """Return the bytes of a requested billing report."""
    path = resolve_report_path(account_id, report_name)
    with open(path, "rb") as handle:
        return handle.read()


def list_reports(account_id: str) -> list:
    """List the report files available to an account."""
    directory = os.path.join(REPORT_ROOT, account_id)
    if not os.path.isdir(directory):
        return []
    return sorted(os.listdir(directory))
''',
    ),
]

CATALOG_BY_ID: dict[str, Vulnerability] = {v.vuln_id: v for v in CATALOG}

CATEGORY_LABELS: dict[str, str] = {
    "pii_exposure": "PII Exposure",
    "rce_dependency": "Vulnerable Dependency / RCE",
    "query_injection": "SQL / Query Injection",
    "secrets_exposure": "Secrets Exposure",
    "insecure_deserialization": "Insecure Deserialization",
    "auth_bypass": "Authentication Bypass",
    "ssrf": "Server-Side Request Forgery",
    "path_traversal": "Path Traversal",
}


def get(vuln_id: str) -> Vulnerability:
    if vuln_id not in CATALOG_BY_ID:
        raise KeyError(vuln_id)
    return CATALOG_BY_ID[vuln_id]


def issue_body(
    vuln: Vulnerability, repo: str, commit_url: str, branch: str
) -> str:
    """Render the GitHub issue body the blue team / Devin will act on."""

    lines = [
        f"## {vuln.title}",
        "",
        f"**Severity:** `{vuln.severity}` | **Category:** "
        f"`{vuln.category}` | **CWE:** `{vuln.cwe}`",
        f"**Repository:** `{repo}`",
        f"**Vulnerable file:** `{vuln.file_path}`",
        f"**Injected on branch:** `{branch}`",
        "",
        "### Description",
        vuln.description,
        "",
        "### Where it lives",
        f"The vulnerable code was added as a self-contained synthetic file at "
        f"`{vuln.file_path}` on branch `{branch}`. No upstream Superset "
        f"code was modified. Any fix pull request must target branch `{branch}` "
        "rather than the default branch.",
    ]
    if commit_url:
        lines += ["", f"Injection commit: {commit_url}"]
    lines += [
        "",
        "### Remediation guidance",
        vuln.remediation,
        "",
        "### Acceptance criteria",
        f"- [ ] `{vuln.file_path}` no longer contains the vulnerable pattern "
        f"({vuln.detection_hint or vuln.category}).",
        "- [ ] The module keeps its public function signatures so callers do "
        "not break.",
        "- [ ] A pull request is opened that closes this issue.",
        "",
        "---",
        "_Synthetic vulnerability injected by the purple-team red service for "
        "autonomous-remediation validation. Not a real production finding._",
    ]
    return "\n".join(lines)
